### PR TITLE
Avoid eager value collection in ChangeMoveSelector 

### LINKED ISSUE #38: Make selected-count limits effective for cursor-based move generation
Hello, awesome solverforge!
This is my first issue, and it's about recent update for `open_cursor` based selector. Please feel free to add any comment 😃 

### Problem
The recent `open_cursor` refactor moves local search toward cursor-based move generation, where moves can be generated and evaluated incrementally.
`SelectedCountLimitMoveSelector` currently limits the number of moves yielded by the wrapped selector:

```rust
  self.inner.open_cursor(score_director).take(self.limit)
```
This satisfies the narrow “yielded move count” contract. However, if the child selector eagerly materializes moves inside `open_cursor` before returning the iterator, the child may still construct more than `self.limit` moves before the limit is applied.
For example, a selector that builds a full `Vec` and returns `moves.into_iter()` will still pay the full generation cost even when wrapped by `SelectedCountLimitMoveSelector`

### Possible Verification
This can be verified with a unit test using existing selector APIs
Wrap `ChangeMoveSelector::simple(...)` with `SelectedCountLimitMoveSelector` and use a test value type that counts Clone calls. The wrapper should yield only limit moves, but the value range may be cloned beyond the limit if the child selector eagerly collects values before yielding moves.

The test should check both:
 - yielded move count is capped at limit
 - value generation or cloning does not exceed limit for a selector that is expected to behave lazily

### Improvement Direction
Convert eager leaf selectors to true lazy cursors, starting with `ChangeMoveSelector` or `ListChangeMoveSelector`. The cursor should own only the small iteration state it needs, such as selected entities, value ranges or route lengths, current source/ destination indices, and function pointers. It should construct each move from `Iterator::next()` instead of prebuilding the full move list. This would make `SelectedCountLimitMoveSelector` useful as a real generation budget when the child selector supports lazy cursor semantics.

### Test Plan
  - Add unit coverage showing that `SelectedCountLimitMoveSelector` caps yielded moves.
  - Add a regression test using an existing selector such as `ChangeMoveSelector::simple(...)` with an instrumented value type to expose
    eager child generation.
  - After converting the target selector to a lazy cursor, assert that only limit values are generated or cloned when wrapped by
    `SelectedCountLimitMoveSelector`.
  - Add correctness coverage that the lazy selector produces the same move sequence as the previous eager implementation on small
    fixtures.

### PR DESCRIPTION
**Pull request by NewBornRustacean**
### Summary
Fixes the interaction between `SelectedCountLimitMoveSelector` and `ChangeMoveSelector` after the recent `open_cursor` refactor. 

closes #38 

### Changes
  - Changed `ChangeMoveSelector::open_cursor` so it no longer eagerly collects all candidate values into Vecs.
  - Add a test case.
  - Kept entity references materialized so the returned cursor does not borrow the score director.
 
### Test Case
The new test uses a `CountedValue` type whose Clone implementation increments a shared counter.

Input setup:
  - one planning entity with an optional counted value
  - `ChangeMoveSelector::simple(...)` with 10 candidate values
  - `SelectedCountLimitMoveSelector` with `limit = 3`

Expected behavior:
  - the limited selector yields exactly 3 moves
  - only 3 candidate values are cloned/generated while consuming the limited iterator

### CODE REVIEW

File: crates/solverforge-solver/src/heuristic/selector/decorator/count_limit_tests.rs [hunk 1]
```diff
@@ -41,3 +56,107 @@ fn zero_limit_yields_nothing() {
...
+    let inner =
+        ChangeMoveSelector::simple(get_counted_value, set_counted_value, 0, "counted", values);
+    let limited = SelectedCountLimitMoveSelector::new(inner, limit);
+
+    let moves: Vec<_> = limited.iter_moves(&director).collect();
+    assert_eq!(moves.len(), limit);
+
+    // if SelectedCountLimitMoveSelector properly limits the inner selector, then only `limit` values should have been cloned.
+    // this is based on the assumption that the selector should limit the child generation of moves.
+    assert_eq!(cloned.load(Ordering::SeqCst), limit);
```
Comment (NewBornRustacean) [inline crates/solverforge-solver/src/heuristic/selector/decorator/count_limit_tests.rs]: @blackopsrepl  what's up 😄 
This is the first review point I guess. This is the assumption that this entire PR relies on: "the selector should limit not only the wrapper's limit but also the child generation of moves"

**Comment by blackopsrepl** [comment]
Thanks for the fix. I pushed two follow-up commits onto this branch.

I kept the `ChangeMoveSelector::open_cursor` change and moved the regression coverage into `move_selector_tests.rs` so the laziness check sits on the selector itself. I also removed `selected_count_limit_move_selector` from the selector decorator surface and replaced it with `limited_neighborhood` in config and runtime. The limit was already being treated as a neighborhood concern by the canonical builder, so this keeps the same move-cap behavior while removing the extra wrapper path.

I updated the affected docs and wireframes in the same change and reran `cargo test -p solverforge-config`, `cargo test -p solverforge-solver`, and `make build` after the refactor.

File: crates/solverforge-solver/src/heuristic/selector/decorator/count_limit_tests.rs (hunk 1 above)
Comment (blackopsrepl) [reply crates/solverforge-solver/src/heuristic/selector/decorator/count_limit_tests.rs]: Yep ! That assumption is very reasonable. This is actually a very good PR.

So, on the code path I just modified, the limit was applied to the cursor, so if ChangeMoveSelector eagerly materialized all candidate values before the cursor advanced, the cap only affected yielded moves and not the work done underneath. That part was wrong, but at least it allowed the error to surface.

Now I changed the branch a bit further than your original patch and removed that wrapper entirely, because the cap belongs at the neighborhood level rather than as a selector decorator. 
So the code is landing in a different shape, but the error you were pointing at was real and the laziness fix in ChangeMoveSelector is still the right part of it. 

Thank you! Releasing this as v0.8.9!
